### ISSUE TITLE
Test JTAG and SWD I/O

### ISSUE THREAD

**Issue by jonas-schievink** [jonas-schievink/jaylink#1]
* [x] JTAG
* [X] SWD

**Comment by Yatekii** [comment]
probe-rs has working JTAG support using this lib, so I guess it can be seen as confirmed working :)

**Comment by jonas-schievink** [comment]
Cool!

**Comment by Yatekii** [comment]
This lib is cool! Was absolutely straightforward to implement SWD in probe-rs with it :)
