### ISSUE TITLE
SWO capture support

### ISSUE THREAD

**Issue by valff** [jonas-schievink/jaylink#13]
Nice crate! Are there any plans for implementing SWO capture?

**Comment by jonas-schievink** [comment]
It looks like revision 7 of the USB protocol docs doesn't document the command for reading SWO (only that it exists). I'd love to support it though!

**Comment by valff** [comment]
I'd like to port it from the C libjaylink. Would you accept a PR?

**Comment by jonas-schievink** [comment]
That unfortunately is GPL code, while this library is licensed under 0-BSD. Is it possible to find out what documentation their code is based on, or whether their reversing results are available somewhere in non-code form?

**Comment by jonas-schievink** [comment]
If all else fails, it should be fine to check out the code to see how the protocol works, and then implement that in Rust. Just a straight port is not okay.

**Comment by valff** [comment]
Ok, I understand. I will try to find the documentation their code is based on.

**Comment by jonas-schievink** [comment]
Implemented in https://github.com/jonas-schievink/jaylink/pull/18.
