### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Tiwalun** [jonas-schievink/jaylink#33]
We're planning to make a new probe-rs release soon, and would need a new jaylink release for that. Unfortunately, we cannot use the released version due to a conflict between the different `rusb` versions in `jaylink` and `probe-rs`. Using an older `rusb` version is not an option due to bugs.

Are you planning to create a new release soon?

**Comment by jonas-schievink** [comment]
Yes, I'll work on this next week

**Comment by Tiwalun** [comment]
Thanks in advance! :heart:

**Comment by jonas-schievink** [comment]
I've published 0.2.0, let me know if there are any issues
